// src/components/Article.svelte
<script lang="ts">
	import { PortableText } from '@portabletext/svelte';
	import { portableTextComponents } from './portableTextComponents';
	import type { PortableTextBlock } from '@portabletext/types';

	export let article: {
		title: string;
		lead?: string;
		illustration?: any;
		prose?: PortableTextBlock[];
		author?: { name: string };
		category?: { title: string };
		metaDescription?: string;
		slug?: { current: string };
		date?: string;
		frontPageQuote?: string;
		source?: string;
		language?: string;
	};

	// Date formatting utility
	const formatDate = (date?: string) => {
		if (!date) return '';
		return new Date(date).toLocaleDateString('no-NO', {
			year: 'numeric',
			month: 'long',
			day: 'numeric'
		});
	};

	// Sanity image URL builder
	import imageUrlBuilder from '@sanity/image-url';
	import { client } from '../lib/sanity-client';

	const builder = imageUrlBuilder(client);
	const urlFor = (source) => builder.image(source).width(1200).url();
</script>

<article class="article">
	<header>
		<h1>{article.title}</h1>

		{#if article.lead}
			<p class="lead">{article.lead}</p>
		{/if}

		{#if article.illustration}
			<img
				src={urlFor(article.illustration)}
				alt={article.illustration.alt || article.title}
				class="illustration"
			/>
		{/if}

		<div class="meta">
			{#if article.date}<time datetime={article.date}>{formatDate(article.date)}</time>{/if}
			{#if article.author}
				• Av <b>{article.author.name}</b>{/if}
			{#if article.category}
				• Tema <b>{article.category.title}</b>{/if}
		</div>
	</header>

	{#if article.prose}
		<PortableText value={article.prose} components={portableTextComponents} />
	{/if}

	{#if article.frontPageQuote}
		<blockquote class="front-quote">
			{article.frontPageQuote}
		</blockquote>
	{/if}

	{#if article.source}
		<footer class="source">
			<p>Kilde: {article.source}</p>
		</footer>
	{/if}
</article>

<style>
	.article {
		max-width: 720px;
		margin: 0 auto;
		padding: 1.5rem;
		font-family: Georgia, serif;
		line-height: 1.6;
	}

	h1 {
		font-size: 2rem;
		margin-bottom: 0.5rem;
	}

	.lead {
		font-size: 1.2rem;
		font-weight: 550;
		color: #555;
		margin-bottom: 1rem;
	}

	.illustration {
		width: 100%;
		height: auto;
		margin: 1rem 0;
		border-radius: 8px;
	}

	.meta {
		font-size: 0.9rem;
		color: #777;
		margin-bottom: 1.5rem;
	}

	.front-quote {
		border-left: 4px solid #aaa;
		padding-left: 1rem;
		font-style: italic;
		margin: 2rem 0;
	}

	.source {
		font-size: 0.85rem;
		color: #666;
		margin-top: 2rem;
	}
</style>

// src/components/Article.tsx
import { PortableText, PortableTextBlock } from "next-sanity";
import imageUrlBuilder from "@sanity/image-url";
import type { SanityImageSource } from "@sanity/image-url/lib/types/types";
import { client } from "@/sanity/client";
const { projectId, dataset } = client.config();

export type ArticleProps = {
    title: string;
    lead: string;
    illustration: SanityImageSource;
    author: string;
    category: string;
    prose: PortableTextBlock[];
    slug: string;
    metaDescription: string;
    date: string;
    source: string;
    language: string;
    _type: "article";
}
const urlFor = (source: SanityImageSource) =>
  projectId && dataset
    ? imageUrlBuilder({ projectId, dataset }).width(250).image(source)
    : null;

export function Article({title, lead, illustration, prose, author, category, date}: ArticleProps) {
return <div>
    <h1>{title}</h1>
    <img src={urlFor(illustration)?.url()} alt={title}></img>
    {author ?
    <dl>
        <dt><b>Forfatter</b></dt>
        <dd key={author}>{author}</dd>
    </dl>

    : null}
{lead ? <div><b>{lead}</b></div> : null}
{prose ? <PortableText value={prose} /> : null }

    <p><small>Publisert: {date}, {category}</small></p>
</div>

}
